export default{
  REQUEST_SENT: 'FOLLOW_REQUEST_SENT',
  FOLLOW_SUCCESS: 'FOLLOW_SUCCESSFUL',
  FOLLOW_FAILIURE: 'FOLLOW_UNSUCCESSFUL',
  GET_FOLLOWERS_SUCCESS: 'GET_FOLLOWERS_SUCCESSFUL',
  GET_FOLLOWING_SUCCESS: 'GET_FOLLOWING_SUCCESSFUL',
  GET_FOLLOW_FAILIURE: 'GET_USERS_UNSUCCESFUL',
};
