export default{
  REQUEST_SENT: 'GET_FOLLOW_STATUS_REQUEST_SENT',
  GET_FOLLOW_STATUS_SUCCESS: 'GET_FOLLOWING_STATUS_SUCCESSFUL',
  GET_FOLLOW_STATUS_FAILIURE: 'GET_FOLLOWING_STATUS_UNSUCCESSFUL',
};
