# Hound CI scss configurations
scss:
  enabled: false

# Hound CI eslint configurations
eslint:
  enabled: true
  config_file: .eslintrc.json

# scss:
#   enabled: true
#   config_file: .scss-lint.yml

# exclude:
#   - "**/*.scss"