# Hound CI eslint configurations
eslint:
  enabled: true
  config_file: .eslintrc.json
scss:
  enabled: false
scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

exclude:
  - "src/styles/*.scss"
  - "styles/styles.scss"
  - "src/styles/scss/components/_articles.scss"
  - "src/styles/scss/components/_.scss"
