# Hound CI eslint configurations
eslint:
  enabled: true
  config_file: .eslintrc.json
scss:
  enabled: false
exclude:
  - "src/styles/*.scss"
  - "src/styles/styles.scss"
  - "src/styles/scss/components/_articles.scss"
