# Hound CI eslint configurations
eslint:
  enabled: true
  config_file: .eslintrc.json
scss:
  enabled: false
scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

exclude:
  - "styles/*.scss"
  - "styles/styles.scss"
