export default{
  NOTIFICATION_SUCCESS: 'FETCH_NOTIFICATIONS_SUCCESSFUL',
  NOTIFICATION_FAILIURE: 'FETCH_NOTIFICATIONS_FAILED',
  NOTIFICATION_REQUEST: 'FETCH_NOTIFICATIONS_REQUEST_SENT',
  READ_NOTIFICATION: 'NOTIFICATION_READ',
};
