// Update user profile
export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const CLEAR_STORE = 'CLEAR_STORE';
