// View user profile
export const VIEW_PROFILE_REQUEST = 'VIEW_PROFILE_REQUEST';
export const VIEW_PROFILE_SUCCESS = 'VIEW_PROFILE_SUCCESS';
export const VIEW_LOGGED_IN_PROFILE_SUCCESS = 'VIEW_LOGGED_IN_PROFILE_SUCCESS';
export const VIEW_PROFILE_FAILURE = 'VIEW_PROFILE_FAILURE';
