export const RATE_ARTICLE = 'RATE_ARTICLE';
export const CURRENT_RATE = 'CURRENT_RATE';
export const RATING_FAILURE = 'RATING_FAILURE';
export const RATING_SUCCESS = 'RATING_SUCCESS';
export const CURRENT_AVG = 'CURRENT_AVG';
