export default {
  UNSUBSCRIBE_SUCCESS: 'UNSUBSCRIBE SUCCESSFUL',
  SUBSCRIBE_SUCCESS: 'SUBSCRIBE SUCCESSFUL',
  UNSUBSCRIBE_FAILED: 'UNSUBSCRIBE FAILURE',
  SUBSCRIBE_FAILED: 'SUBSCRIBE FAILURE',
};
